// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgu6o9X6wd_S2PNBAT9zHyHFUvb8yeuVI',
    appId: '1:268004035751:web:08aef301d3068b5c9c9f82',
    messagingSenderId: '268004035751',
    projectId: 'friendi-ai',
    authDomain: 'friendi-ai.firebaseapp.com',
    storageBucket: 'friendi-ai.firebasestorage.app',
    measurementId: 'G-9XZSEHCMH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJtjAAgx9l50_kbyGB9_Re1sTlg4a_EE',
    appId: '1:268004035751:android:c7a5ad11c3f84ac59c9f82',
    messagingSenderId: '268004035751',
    projectId: 'friendi-ai',
    storageBucket: 'friendi-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKSMLC_uayRkh1FzwfAaDffbPmBs_iu-M',
    appId: '1:268004035751:ios:9bb2b7f97e05955e9c9f82',
    messagingSenderId: '268004035751',
    projectId: 'friendi-ai',
    storageBucket: 'friendi-ai.firebasestorage.app',
    iosBundleId: 'com.example.friendiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKSMLC_uayRkh1FzwfAaDffbPmBs_iu-M',
    appId: '1:268004035751:ios:9bb2b7f97e05955e9c9f82',
    messagingSenderId: '268004035751',
    projectId: 'friendi-ai',
    storageBucket: 'friendi-ai.firebasestorage.app',
    iosBundleId: 'com.example.friendiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgu6o9X6wd_S2PNBAT9zHyHFUvb8yeuVI',
    appId: '1:268004035751:web:18ec397abfe01ced9c9f82',
    messagingSenderId: '268004035751',
    projectId: 'friendi-ai',
    authDomain: 'friendi-ai.firebaseapp.com',
    storageBucket: 'friendi-ai.firebasestorage.app',
    measurementId: 'G-L2LYR7TV3P',
  );
}
